### PR TITLE
WIP: Add CAS Single Logout

### LINKED ISSUE #16: Add an event listener for Single Logout (SLO)
It should be possible to handle single logout signals from CAS servers as documented in the [spec](https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol-Specification.html#233-single-logout). This could perhaps be something that could be activated in the service container optionally.

### PR DESCRIPTION
**Pull request by junowilderness**
Fixes #16

### CODE REVIEW

**Comment by junowilderness** [comment]
I just now realized that in my zeal to code this up, I confused CAS Ticket Granting Ticket (session key) with PHP session IDs! Any implementation of single logout has to store these upon authentication so the correct session can be terminated on single logout.

So this needs a lot of work.

**Comment by connorhu** [comment]
There are several problems with your implementation:
- the samlp:SessionIndex contains the service ticket (ST-*) not the session id
- as you can see in the schema specification the samlp:SessionIndex max occurences is unbounded so the server can send multiple STs.
https://docs.oasis-open.org/security/saml/v2.0/saml-schema-protocol-2.0.xsd
- the login method should save the ST - php session id pair
- your code does not works with the non-native session handlers (PDO, redis, memcache etc)

**Comment by junowilderness** [comment]
It’s generous to call it an “implementation” as it doesn’t even work.

**Comment by connorhu** [comment]
I've started to play a little bit with this issue. If you want to keep at low the footprint of the changes, you can make a simple notification about the succesfull service ticket validation:
https://github.com/connorhu/CasAuthBundle/commit/70d7c04d034a53346e8cb8aba3faadf3493abcbe

The subscriber saves the ticket into the session, and an other requeset listener catches the SLO logout request. At this point the request listener needs to browse every live sessions. My example works with redis handler, but with driver pattern we can make the cleanup process for every handler type.

**Pull request closed without merging**
